# Independent, solver-free Research production DAG. Source paths identify frozen
# inputs; electric_base, fragment and carbon map are generated by these rules.
ROOT = "results_project/assembly_v1"
from pathlib import Path
ALLOC = ROOT + "/allocation"
ASSETS = ROOT + "/assets"
if config.get("reuse_allocation") and Path(config["reuse_allocation"]).resolve() == Path(ALLOC).resolve():
    raise ValueError("reuse_allocation must be an immutable prior allocation directory, not this rule's outputs")

rule research_fullsc_unsolved:
    input:
        ROOT + "/research_fullsc_2050_assembly_v1_unsolved.nc",

rule research_allocate_inputs:
    input:
        registry="research_inputs/assembly_v1/registry.json",
        reference=lambda w: config["source_reference"],
        ports=lambda w: config["source_ports"],
        airports=lambda w: config["source_airports"],
    output:
        manifest=ALLOC + "/allocation_manifest.json",
        arrays=ALLOC + "/allocations.npz",
        nodes=ALLOC + "/geographic_nodes.json",
    params:
        reuse=lambda w: ("--reuse " + __import__("shlex").quote(config["reuse_allocation"]) + " --reuse-registry " + __import__("shlex").quote(config["reuse_registry"])) if config.get("reuse_allocation") else "",
    shell:
        "python scripts_project/allocate_assembly_inputs.py --registry {input.registry:q} --reference {input.reference:q} --ports {input.ports:q} --airports {input.airports:q} --output " + ALLOC + " {params.reuse}"

rule research_build_production_assets:
    input:
        reference=lambda w: config["source_reference"],
        costs=lambda w: config["source_costs2050"],
        price_layer=ASSETS + "/model_cost_layer.json",
        fixed_accounts_code="scripts_project/fixed_accounts.py",
        price_code="scripts_project/price_basis.py",
        oldcosts=lambda w: config["source_costs2030_electric"],
        allocation=ALLOC + "/allocation_manifest.json",
        arrays=ALLOC + "/allocations.npz",
        registry="research_inputs/assembly_v1/registry.json",
        builder="scripts_project/build_research_assets.py",
        architecture="scripts_project/carrier_architecture.py",
        existing_integration="scripts_project/integrate_surviving_assets.py",
        existing_selector="scripts_project/asset_survival.py",
        selected_code="scripts_project/selected_closure.py",
        selected_decisions="research_inputs/asset_survival/selected_closure_decisions.json",
        integration_contract=ASSETS + "/SELECTED_INTEGRATION_CONTRACT.json",
        survival=ASSETS + "/SELECTED_ASSET_SURVIVAL_2050.json",
        research_config="configs/research/baseline.yaml",
        upstream_config="configs/config.asean.yaml",
        default_config="config.default.yaml",
    output:
        bundle=ASSETS + "/asset_bundle.json",
        electric=ASSETS + "/electric_base_2050_unsolved.nc",
        fragment_nc=ASSETS + "/carrier_fragment_2050_unsolved.nc",
        carrier=ASSETS + "/carrier_fragment.json",
        carbon=ASSETS + "/carbon_component_map.json",
        destinations=ASSETS + "/demand_destinations.json",
        electric_manifest=ASSETS + "/ELECTRIC_BASE_ASSET_MANIFEST.json",
        fragment_manifest=ASSETS + "/GATE3_PRODUCTION_FRAGMENT_MANIFEST.json",
        external_fixed=ASSETS + "/external_pending_fixed_accounts.json",
        accounting=ASSETS + "/accounting_qualification.json",
    shell:
        "python scripts_project/build_research_assets.py --repo . --reference {input.reference:q} --costs {input.costs:q} --oldcosts {input.oldcosts:q} --survival {input.survival:q} --integration-contract {input.integration_contract:q} --price-layer {input.price_layer:q} --allocation " + ALLOC + " --output " + ASSETS

rule research_prepare_hydro_groups:
    input:
        reference=lambda w: config["source_reference"],
        costs=lambda w: config["source_costs2030_electric"],
        survival=ASSETS + "/ASSET_SURVIVAL_2050.json",
        contract="research_inputs/asset_survival/integration_contract.json",
        decisions="research_inputs/asset_survival/hydro_decisions.json",
        script="scripts_project/prepare_hydro_group_contract.py",
    output:
        contract=ASSETS + "/HYDRO_INTEGRATION_CONTRACT.json",
        report=ASSETS + "/HYDRO_GROUP_QUALIFICATION.json",
    shell:
        "python scripts_project/prepare_hydro_group_contract.py --repo . --reference {input.reference:q} --costs {input.costs:q} --survival {input.survival:q} --contract {input.contract:q} --decisions {input.decisions:q} --output {output.contract:q} --report {output.report:q}"

rule research_trace_existing_assets:
    input:
        plants=lambda w: config["source_powerplants"],
        tracer="scripts_project/trace_asset_survival.py",
        unit_selector="scripts_project/unit_asset_survival.py",
        age_selector="scripts_project/asset_survival.py",
        decisions="research_inputs/asset_survival/lifetime_decisions.json",
        lifetime_config="configs/powerplantmatching_config.yaml",
        raw_cache=lambda w: sorted(str(p) for p in Path(config["source_plant_cache"]).glob("*.xlsx")),
    params:
        cache=lambda w: config["source_plant_cache"],
    output:
        ASSETS + "/ASSET_SURVIVAL_2050.json",
    shell:
        "python scripts_project/trace_asset_survival.py --repo . --plants {input.plants:q} --cache {params.cache:q} --lifetimes {input.decisions:q} --output {output:q}"

rule research_prepare_common_price_year:
    input:
        index="research_inputs/prices/sources/ECB_EA20_GDP_DEFLATOR.csv",
        policy="research_inputs/prices/decision.json",
        script="scripts_project/price_basis.py",
        raw2050=lambda w: str(Path(config["source_costs2050"]).with_name("costs_2050.csv")),
        raw2030=lambda w: str(Path(config["source_costs2030_electric"]).with_name("costs_2030.csv")),
        prepared2050=lambda w: config["source_costs2050"],
        prepared2030=lambda w: config["source_costs2030_electric"],
        upstream_evidence=lambda w: [str(Path(config["technology_data_evidence"])/p) for p in ["outputs/costs_2030.csv","outputs/costs_2050.csv","config.yaml","scripts/compile_cost_assumptions.py","scripts/_helpers.py"]],
    output:
        ASSETS + "/model_cost_layer.json",
    params:
        costdir=lambda w: str(Path(config["source_costs2050"]).parent),
        technology_data=lambda w: config["technology_data_evidence"],
    shell:
        "python scripts_project/price_basis.py --costdir {params.costdir:q} --technology-data {params.technology_data:q} --index-file {input.index:q} --output {output:q}"

rule research_apply_selected_closure:
    input:
        reference=lambda w: config["source_reference"],
        survival=ASSETS + "/ASSET_SURVIVAL_2050.json",
        contract=ASSETS + "/HYDRO_INTEGRATION_CONTRACT.json",
        decisions="research_inputs/asset_survival/selected_closure_decisions.json",
        cohorts="research_inputs/asset_survival/GPD_COHORT_SOURCE_REVIEW.json",
        identities="research_inputs/asset_survival/GEM_FROZEN_IDENTITY_FIELDS.json",
        script="scripts_project/apply_selected_stock.py",
        methods="scripts_project/selected_closure.py",
        lifetime_overrides="research_inputs/asset_survival/asset_lifetime_overrides.json",
        lifetime_override_code="scripts_project/asset_lifetime_override.py",
    output:
        stock=ASSETS + "/SELECTED_ASSET_SURVIVAL_2050.json",
        contract=ASSETS + "/SELECTED_INTEGRATION_CONTRACT.json",
        report=ASSETS + "/SELECTED_CLOSURE_IMPLEMENTATION.json",
    shell:
        "python scripts_project/apply_selected_stock.py --repo . --reference {input.reference:q} --survival {input.survival:q} --contract {input.contract:q} --decisions {input.decisions:q} --cohort-evidence {input.cohorts:q} --output-stock {output.stock:q} --output-contract {output.contract:q} --output-report {output.report:q}"

# Explicit separate target. It never supplies the full-model rule's output.
rule research_build_diagnostic_network:
    input:
        bundle=ASSETS + "/asset_bundle.json",
        electric=ASSETS + "/electric_base_2050_unsolved.nc",
        carrier=ASSETS + "/carrier_fragment.json",
        carbon=ASSETS + "/carbon_component_map.json",
        fixed=ASSETS + "/external_pending_fixed_accounts.json",
        price=ASSETS + "/model_cost_layer.json",
        stock=ASSETS + "/SELECTED_ASSET_SURVIVAL_2050.json",
        contract=ASSETS + "/SELECTED_INTEGRATION_CONTRACT.json",
        registry="research_inputs/assembly_v1/registry.json",
        pins="research_inputs/assembly_v1/manifest.json",
        allocation=ALLOC + "/allocation_manifest.json",
        arrays=ALLOC + "/allocations.npz",
        current="research/04_model_assembly/gate4/CURRENT_GATE4_SELECTED_MANIFEST.json",
        coverage="research/04_model_assembly/gate4/evidence/selected/SOURCE_COVERAGE_ACCOUNT_MAP_CURRENT.json",
        scope_code="scripts_project/source_scope.py",
        scope_decisions="research_inputs/assembly_v1/sources/BOUNDED_SOURCE_SCOPE_DECISIONS.json",
        scope_proof="research_inputs/assembly_v1/sources/BOUNDED_SOURCE_SCOPE_APPLICATION.json",
        gate_code="scripts_project/check_assembly_inputs.py",
        assembler="scripts_project/build_diagnostic_network.py",
        shared="scripts_project/assembly_components.py",
    output:
        network=ROOT + "/research_2050_diagnostic_partial_unsolved.nc",
        report=ROOT + "/DIAGNOSTIC_NETWORK_MANIFEST.json",
        readiness=ROOT + "/CURRENT_PHYSICAL_READINESS.json",
    shell:
        "python scripts_project/build_diagnostic_network.py --repo . --allocation " + ALLOC + " --assets {input.bundle:q} --output {output.network:q} --report {output.report:q} --readiness {output.readiness:q}"

include: "research_final_assembly.smk"
