# Independent, solver-free Research production DAG. Source paths identify frozen
# inputs; electric_base, fragment and carbon map are generated by these rules.
ROOT = "results_project/assembly_v1"
from pathlib import Path
ALLOC = ROOT + "/allocation"
ASSETS = ROOT + "/assets"

rule research_fullsc_unsolved:
    input:
        registry="research_inputs/assembly_v1/registry.json",
        pins="research_inputs/assembly_v1/manifest.json",
        allocation=ALLOC + "/allocation_manifest.json",
        arrays=ALLOC + "/allocations.npz",
        assets=ASSETS + "/asset_bundle.json",
        electric=ASSETS + "/electric_base_2050_unsolved.nc",
        carrier=ASSETS + "/carrier_fragment.json",
        carbon=ASSETS + "/carbon_component_map.json",
    output:
        network=ROOT + "/research_fullsc_2050_unsolved.nc",
        report=ROOT + "/build_receipt.json",
    shell:
        "python scripts_project/build_research_network.py --repo . --allocation " + ALLOC + " --assets {input.assets:q} --output {output.network:q} --report {output.report:q}"

rule research_allocate_inputs:
    input:
        registry="research_inputs/assembly_v1/registry.json",
        reference=lambda w: config["source_reference"],
        ports=lambda w: config["source_ports"],
        airports=lambda w: config["source_airports"],
    output:
        manifest=ALLOC + "/allocation_manifest.json",
        arrays=ALLOC + "/allocations.npz",
        nodes=ALLOC + "/geographic_nodes.json",
    params:
        reuse=lambda w: ("--reuse '" + config["reuse_allocation"].replace("'", "'\"'\"'") + "'") if config.get("reuse_allocation") else "",
    shell:
        "python scripts_project/allocate_assembly_inputs.py --registry {input.registry:q} --reference {input.reference:q} --ports {input.ports:q} --airports {input.airports:q} --output " + ALLOC + " {params.reuse}"

rule research_build_production_assets:
    input:
        reference=lambda w: config["source_reference"],
        costs=lambda w: config["source_costs2050"],
        oldcosts=lambda w: config["source_costs2030_electric"],
        allocation=ALLOC + "/allocation_manifest.json",
        arrays=ALLOC + "/allocations.npz",
        registry="research_inputs/assembly_v1/registry.json",
        builder="scripts_project/build_research_assets.py",
        architecture="scripts_project/carrier_architecture.py",
        survival=ASSETS + "/ASSET_SURVIVAL_2050.json",
        research_config="configs/research/baseline.yaml",
        upstream_config="configs/config.asean.yaml",
        default_config="config.default.yaml",
    output:
        bundle=ASSETS + "/asset_bundle.json",
        electric=ASSETS + "/electric_base_2050_unsolved.nc",
        fragment_nc=ASSETS + "/carrier_fragment_2050_unsolved.nc",
        carrier=ASSETS + "/carrier_fragment.json",
        carbon=ASSETS + "/carbon_component_map.json",
        destinations=ASSETS + "/demand_destinations.json",
        electric_manifest=ASSETS + "/ELECTRIC_BASE_ASSET_MANIFEST.json",
        fragment_manifest=ASSETS + "/GATE3_PRODUCTION_FRAGMENT_MANIFEST.json",
    shell:
        "python scripts_project/build_research_assets.py --repo . --reference {input.reference:q} --costs {input.costs:q} --oldcosts {input.oldcosts:q} --survival {input.survival:q} --allocation " + ALLOC + " --output " + ASSETS

rule research_trace_existing_assets:
    input:
        plants=lambda w: config["source_powerplants"],
        tracer="scripts_project/trace_asset_survival.py",
        lifetime_config="configs/powerplantmatching_config.yaml",
        raw_cache=lambda w: sorted(str(p) for p in Path(config["source_plant_cache"]).glob("*.xlsx")),
    params:
        cache=lambda w: config["source_plant_cache"],
    output:
        ASSETS + "/ASSET_SURVIVAL_2050.json",
    shell:
        "python scripts_project/trace_asset_survival.py --repo . --plants {input.plants:q} --cache {params.cache:q} --output {output:q}"
