"""Extract traceable register records; output JSON intermediate, never model inputs."""
from pathlib import Path
import csv,json
R=Path(__file__).resolve().parent; U=R/'source_snapshot/upstream'; rows=[]
def add(p,v,unit,key,src,region,asean,used,reason,category='DEFAULT_WITHOUT_ASEAN_EVIDENCE',judgment='ASEAN_VALIDATION_PENDING',year='UNSPECIFIED',transform='As stored; not changed'):
    rows.append(dict(Parameter=p,Value=str(v),Unit=unit,Config_Key=key,Source=src,Source_Region=region,ASEAN_Specific=asean,Used_In_Frozen_SHA=used,Status='UNVERIFIED',Reason=reason,Source_Classification=category,Audit_Judgment=judgment,Reference_Year=year,Transformation=transform,Human_Acceptance='PENDING',Evidence_Layer='F/U; T/P applicability explained in reports',Frozen_SHA='a3616a68ee44592af6527ca9024a90f1956646ae'))
pre='YES: preparation/pre-final-pruning; final heat removed'
add('Demand base year',2019,'year','demand_data.base_year','config.default.yaml; scripts/build_base_energy_totals.py','Global with ASEAN records','Country rows, not heat end-use validation','YES','Raw balance year differs from file export date','RECOVERED_SOURCE','SOURCE_RECOVERED','2019')
add('Space heating share',.6,'fraction','sector.space_heat_share','config.default.yaml:849; history/SPLIT_ORIGINAL_COMMIT.txt','Earth-Sec default','NO',pre,'Common for R/S and all countries; underlying statistical justification not recovered',judgment='REJECT_DEFAULT')
add('Coal shift to electricity','true','boolean','sector.coal.shift_to_elec','config.default.yaml:807; scripts/build_base_energy_totals.py','Earth-Sec default','NO','YES: both R/S electricity totals','Coal energy added 1:1; if false coal ignored',judgment='REJECT_DEFAULT',transform='Coal final TWh added to electricity TWh')
for f in ['oil','biomass','gas']:
    add('Heat '+f+' conversion to electricity',.9,'energy ratio, basis unresolved','sector.efficiency_heat_'+f+'_to_elec','config.default.yaml; scripts/prepare_energy_totals.py','Earth-Sec default','NO',pre,'Applied only to shifted heat part; not heat-pump COP',judgment='SCIENTIFIC_DECISION_REQUIRED')
for table in ['fuel_shares','growth_factors_cagr','efficiency_gains_cagr','district_heating']:
    with (U/f'data/demand/{table}.csv').open(newline='') as fh:
        data=list(csv.DictReader(fh)); default=next(r for r in data if str(next(iter(r.values()))).strip()=='DEFAULT')
    for key,value in list(default.items())[1:]:
        if table in ['growth_factors_cagr','efficiency_gains_cagr'] and not any(k in key for k in ['residential','services']):continue
        used=pre;reason='No ASEAN row: each configured country inherits DEFAULT'
        if table=='district_heating' and key=='potential':used='NO: column not consumed by current heat pathway';reason='Do not confuse this unused column with sector.district_heating.potential'
        add(f'{table}: {key}',value.strip(),'fraction/year' if 'cagr' in table else 'fraction',f'data/demand/{table}.csv:DEFAULT:{key}',f'data/demand/{table}.csv','Default; no established geographic calibration','NO',used,reason,judgment='REJECT_DEFAULT',transform='(1+x)^(planning_year-2019)' if 'cagr' in table else 'Fallback DEFAULT then used in formulas')
for key,value,reason in [('potential',.3,'Fraction of urban heat allocated to central supply'),('progress',1,'Actual formula: 1 reaches target; config comment about -1 inconsistent'),('district_heating_loss',.15,'Adds 15% to delivered heat; not division by 0.85')]:
    add('District heating '+key,value,'fraction','sector.district_heating.'+key,'config.default.yaml:825-834; scripts/prepare_sector_network.py:2552-2735','Inherited Earth-Sec/Earth','NO',pre,reason,judgment='REJECT_DEFAULT')
add('Heat profile','24 x 8 BDEW factors','dimensionless shape','Snakefile.prepare_heat_data.input.heat_profile','data/heat_load_profile_BDEW.csv; evidence/PROFILE_SOURCE_RECOVERY.json','Germany / European model inheritance','NO',pre,'Numeric match to Eur-Sec v0.7.0; exact original generation settings unresolved','EUROPE_SPECIFIC','ASEAN_VALIDATION_PENDING')
add('Water heating hourly shape',1,'constant relative weight','BDEW water columns','data/heat_load_profile_BDEW.csv','Inherited European model template','NO',pre,'All 24 hours, both sectors, weekday and weekend equal 1','EUROPE_SPECIFIC','REJECT_DEFAULT')
for p,v,unit in [('threshold',15,'degC'),('a',1,'relative slope'),('constant',0,'relative demand'),('hour_shift',0,'hours UTC shift')]:
    add('Atlite heat-demand '+p,v,unit,'atlite.heat_demand default (not explicit config)','evidence/installed_atlite_heat_demand.py; scripts/build_heat_demand.py','Generic degree-day model','NO','Implicit in U script; observed installed atlite 0.4.1','Dependency default; author original environment not asserted','RECOVERED_SOURCE','ASEAN_VALIDATION_PENDING',transform='daily max(15-temperature_C,0) with a=1, constant=0')
add('BDEW timezone','first national pytz timezone','timezone rule','generate_periodic_profiles','scripts/prepare_heat_data.py','Country-selected, one timezone','PARTIAL',pre,'Multiple-timezone countries not resolved by node','RECOVERED_SOURCE','ENGINEERING_ISSUE')
add('Annual heat nodal allocation','population fraction','fraction','pop_layout.fraction','scripts/build_clustered_population_layouts.py; scripts/prepare_heat_data.py','Global population coverage','PARTIAL',pre,'Same R/S shares; not building-floor-area or end-use allocation','RECOVERED_SOURCE','ASEAN_VALIDATION_PENDING')
add('Population raster year',2020,'year','build_shape_options.year','evidence/CONFIG_LAYERS.json; scripts/build_shapes.py','WorldPop global','PARTIAL',pre,'Country coverage is not building demand validation','RECOVERED_SOURCE','ASEAN_VALIDATION_PENDING','2020')
add('Urban population fraction','country / horizon series','fraction','prepare_urban_percent; pop_layout.urban','scripts/prepare_urban_percent.py; UNCTAD US.PopTotal','Global, country specific','Country rows',pre,'Public live API; download version not pinned; spatial split by density','RECOVERED_SOURCE','ASEAN_VALIDATION_PENDING')
add('Base load spatial weights','GDP 0.6; population 0.4','relative weights','build_demand_profiles.upsample','scripts/build_demand_profiles.py:399-418','EU regression per source comment','NO','YES base-profile spatial allocation','Different allocation from annual heat; no ASEAN regression','EUROPE_SPECIFIC','ASEAN_VALIDATION_PENDING')
add('Existing heating stock','EU28+3; ASEAN absent; DEFAULT blanks -> 0','GW raw; MW prepared','build_existing_heating_distribution','data/existing_infrastructure/existing_heating_raw.csv; EC WP2 201603','Europe','NO','Preparation only; baseyear call commented','Zero is fallback, not observed ASEAN capacity','EUROPE_SPECIFIC','REJECT_DEFAULT','2012',transform='fillna(0); x1000; population and heat-sector fraction')
add('Existing stock urban fraction','pop_layout.fraction','national node share used as urban share','build_existing_heating_distribution','scripts/build_existing_heating_distribution.py:114','Code logic','NO','Dormant capacity insertion; preparation path exists','Wrong semantic field','RECOVERED_SOURCE','ENGINEERING_ISSUE')
add('Existing heating default lifetime',20,'years','existing_capacities.default_heating_lifetime','config.default.yaml:713; scripts/add_existing_baseyear.py','Inherited default','NO','NO active insertion: main call commented','Historical grouping not validated for ASEAN','RECOVERED_SOURCE','SCIENTIFIC_DECISION_REQUIRED')
add('HP sink temperature',55,'degC','sector.heat_pump_sink_T','config.default.yaml:868; scripts/build_cop_profiles.py','DTU / large-area radiators comment','NO',pre,'Staffell 2012 quadratic COP; not reversible cooling','EUROPE_SPECIFIC','ASEAN_VALIDATION_PENDING')
for p,v,unit in [('tes_tau.decentral',3,'days'),('tes_tau.central',180,'days'),('solar_thermal_collector.cf_correction',.788457,'multiplier'),('solar_thermal_collector.orientation.slope',45,'degrees'),('solar_thermal_collector.orientation.azimuth',180,'degrees')]:
    add(p,v,unit,'sector.'+p,'config.default.yaml:851-869','Inherited default','NO',pre,'Affects competition and profiles; no ASEAN validation recovered')
add('Explicit building cooling','absent','component boundary','No cooling switch','history/COOLING_CODE_SEARCH.txt; scripts/prepare_sector_network.py','Model structure','NOT APPLICABLE','No independent cooling component','Aggregate electricity cooling content unquantified','RECOVERED_SOURCE','SCIENTIFIC_DECISION_REQUIRED')
add('Electric heat subtraction','commented out','accounting operation','prepare_heat_data electric_heat_supply','scripts/prepare_heat_data.py:201-220','Model structure','NOT APPLICABLE','NO active subtraction','Quantity not returned/exported; no accepted existing electric-heat bridge','RECOVERED_SOURCE','ENGINEERING_ISSUE')
add('Final electricity-only pruning','true','boolean','final_adjustment.only_elec_network','configs/config.asean.yaml:262','ASEAN configuration','Config specific, not data validation','YES: final heat removed','All three layers U/T/P true; not a full-SC scientific baseline','RECOVERED_SOURCE','ENGINEERING_ISSUE')
(R/'ASSUMPTION_RECORDS.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
print(f'{len(rows)} records, all UNVERIFIED')
