"""Build documentary inventory/provenance/options, never model inputs."""
from pathlib import Path
import json,hashlib,shutil
R=Path(__file__).resolve().parent;ROOT=R.parents[3];D=R/'data';D.mkdir(exist_ok=True)
def save(name,rows):(D/(name+'.json')).write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf8')
U='a3616a68ee44592af6527ca9024a90f1956646ae'
github=f'https://github.com/pypsa-meets-earth/pypsa-asean/blob/{U}/'
cache=json.loads((R/'evidence/CACHED_DEMAND_EVIDENCE.json').read_text(encoding='utf8'))

# Inventory classification is explicitly tied to scope, not all to one network.
specs=[
('ROAD_AGG','Aggregate land EV','EXPLICIT_CURRENT','true; EV share>0 after2020','EV Bus/Load + charger/V2G; Store in constructor','EV/charger/V2G kept; EV Store stripped','98 EV +98 charger +98 V2G; EV Store0','ABSENT: tutorial land=false','road final energy + non-electric rail energy proxy','electricity','No passenger/freight separation; not verified useful mobility','2311–2550'),
('ROAD_PASS','Road passenger','EMBEDDED','aggregate land enabled','No separate passenger component','Inside unresolved aggregate road demand','No distinct passenger Load','No land aggregate','Unsplit aggregate final energy','mixed','No passenger-km or occupancy factor; independent quantity UNKNOWN','2311–2550'),
('ROAD_FREIGHT','Road freight','EMBEDDED','aggregate land enabled','No separate freight component','Inside unresolved aggregate road demand','No distinct freight Load','No land aggregate','Unsplit aggregate final energy','mixed','No tonne-km or load factor; independent quantity UNKNOWN','2311–2550'),
('ROAD_ICE','Road ICE','SUPPORTED_NOT_ACTIVE','residual share=1-EV-FCEV','Fixed oil Load + CO2 Load','Stripped','ABSENT','ABSENT','q/specified efficiency × residual share','oil','Share exogenous; zero2050 residual does not validate source chain','2520–2548'),
('ROAD_FCEV','Road FCEV','SUPPORTED_NOT_ACTIVE','DEC share0','Fixed H2 Load if share>0','Stripped if constructed','ABSENT','ABSENT','q/specified fuel-cell efficiency × share','H2','No endogenous vehicle choice','2504–2518'),
('RAIL_E','Rail electricity','EXPLICIT_CURRENT','true','Fixed electricity Load','Kept','98 Loads both samples','48 Loads pre and final','UNSD final electricity TWh/year','electricity','No parent-electricity subtraction','3696–3739'),
('RAIL_O','Rail non-electric','SUPPORTED_NOT_ACTIVE','true','Fixed oil Load','Stripped','ABSENT','48 pre;0 final','total rail minus electricity rail','oil','Land overlap and CO2 omission risk','3696–3739'),
('SHIP_DOM','Domestic shipping','SUPPORTED_NOT_ACTIVE','true','Combined domestic+international oil/H2 Loads','Stripped','ABSENT','Combined demand present pre;removed final','UNSD final fuel TWh/year','oil;H2','Domestic not independent node Load; no service fleet','1683–1850'),
('SHIP_INT','International shipping','SUPPORTED_NOT_ACTIVE','true; bunkers flag does not disable demand','Combined fuel Loads','Stripped','ABSENT','Combined demand present pre;removed final','UNSD international marine bunkers TWh/year','oil;H2','Bunker obligation/accounting requires decision','1683–1850'),
('SHIP_H2','Shipping hydrogen','SUPPORTED_NOT_ACTIVE','DEC share0; liquefaction=false','H2 Load; optional liquefaction Link','Stripped','ABSENT','47 structural zero +1 NaN pre;0 final','Exogenous share and efficiency conversion','H2','No endogenous ship fuel choice','1733–1785'),
('AVI_DOM','Domestic aviation','SUPPORTED_NOT_ACTIVE','true','Combined kerosene-labelled oil Load','Stripped','ABSENT','48 combined Loads pre;0 final','UNSD kerosene-type fuel TWh/year','oil','No passenger/freight/aircraft split','1545–1628'),
('AVI_INT','International aviation','SUPPORTED_NOT_ACTIVE','true; bunkers flag does not disable demand','Combined kerosene-labelled oil Load','Stripped','ABSENT','48 combined Loads pre;0 final','UNSD international aviation bunkers TWh/year','oil','Bunker scope and carbon weighting unresolved','1545–1628'),
('FT_SUPPLY','Synthetic oil supply','EXPLICIT_CURRENT','fischer_tropsch=true','Extendable multiport Link H2+CO2+AC to oil','Kept supply path','FT supply components present; no transport oil Load','Supply path present; no final transport oil Load','Fuel production; not final mobility demand','H2;CO2;electricity;oil','Existence is not evidence of transport synthetic-fuel use','344–380'),
('NH3_MARINE','Direct ammonia shipping','ABSENT','No dedicated switch/path','Industrial Haber-Bosch/cracker only','No marine ammonia Load','ABSENT','ABSENT','No explicit marine demand','ammonia','Industrial NH3 capability is not shipping NH3','2146–2235'),
('METHANOL','Transport methanol','ABSENT','No dedicated path found','Absent in inspected constructor','Absent','ABSENT','ABSENT','No mode-specific demand','methanol','Bounded to inspected P/U; no new technology authorized','1545–1850'),
('BIOFUEL','Mode-specific biofuel choice','ABSENT','Generic biomass enabled separately','No dedicated transport blend/choice module','No explicit transport blend','ABSENT','ABSENT','Some raw fuels aggregate into total energy','biofuels','Do not infer SAF from generic biomass','2311–2550'),
('EV_STORE','EV DSM storage','SUPPORTED_NOT_ACTIVE','bev_dsm=true','Fixed cyclic Store with SOC restriction','Store carrier not in final whitelist','0 EV Stores both samples','0 (land disabled)','cars × battery MWh × participating fraction × EV share','Li ion','Final V2G Link is not cross-time storage','2484–2502'),
('OTHER_E','Other electric transport','UNKNOWN','No separately identified source/account','No distinct audited constructor','Unknown coverage inside parent demand','No separately identifiable Load','No separately identifiable Load','UNKNOWN','electricity','Cannot assert zero or claim resolved A* overlap','2311–2550')]
inventory=[]
for id,mode,cls,switch,comp,final,author,tutorial,demand,carrier,lim,lines in specs:
 inventory.append(dict(ModeID=id,Mode=mode,Classification=cls,ClassificationScope='Observed author final when EXPLICIT_CURRENT; otherwise inspected framework/account aggregation',UConfig=switch,FrameworkComponents=comp,UFinalPrediction=final,UActualFinalNetwork='UNKNOWN_NOT_BUILT_THIS_PHASE',Author2025_2050Observed=author,Tutorial2030Observed=tutorial,DemandDefinition=demand,Carrier=carrier,Limitation=lim,Evidence='evidence/source/U/scripts/prepare_sector_network.py:'+lines+'; NETWORK_TRANSPORT_EVIDENCE.json',NumericAcceptance='PENDING'))
save('TRANSPORT_MODE_INVENTORY',inventory)

provenance=[]
for i,r in enumerate(cache['conversion_comparison'],1):
 c,f=r['country'],r['field'];v=r['base_text'];missing=r['blank_is_not_zero'];noobs=r['zero_has_no_selected_raw_row']
 mode='road' if 'road' in f else 'rail' if 'rail' in f else 'shipping' if 'navigation' in f else 'aviation'
 provenance.append(dict(ParameterID=f'BASE_{i:03}',Mode=mode,Country=c,Parameter=f,SourceClass='GLOBAL_HARMONIZED',SourceName='UNSD energy statistics; retained tutorial cache',SourceURL='https://data.un.org/Explorer.aspx?d=EDATA',SourceFile='evidence/cached_inputs/resources/baseline-aims-3H-tutorial/energy_totals_base.csv',SourceYear='2019',RawValue='NO_MATCHING_RAW_OBSERVATION' if noobs or missing else f'See immutable raw rows; selected count={r["selected_raw_count"]}',RawUnit='Per original raw row; kt / million kWh / TJ',Transformation='raw units to TWh, select transaction/commodity, sum and round4; see conversion_comparison',PyPSAValue=v,PyPSAUnit='TWh/year final energy',FinalCandidateValue='',Status='UNVERIFIED',HumanConfirmation='PENDING',EvidenceLocator=f'evidence/CACHED_DEMAND_EVIDENCE.json: conversion_comparison[{i-1}], tables.base.{c}.{f}, raw_rows',Issue='MISSING_NOT_ZERO' if missing else 'ZERO_FROM_EMPTY_SUBSET_NOT_OBSERVED_ZERO' if noobs else 'Cache conversion matches; completeness/heat-value/source acceptance still pending'))
params=[
('DEFAULT_GROWTH','all','DEFAULT','Growth CAGR','DEFAULT row; road0.01390; rail0.04940; rail electricity0.03982; aviation domestic0.03715/international0.02156; navigation domestic0.006453/international0.02504','fraction/year','data/demand/growth_factors_cagr.csv','35–109','(1+CAGR)^(target−2019); every ASEAN country inherits DEFAULT','No geographic calibration or ASEAN forecast verification'),
('DEFAULT_EFF','all','DEFAULT','Efficiency CAGR','DEFAULT row; road EV−0.06140/FCEV−0.02652/ICE0; navigation oil−0.001062/H2−0.008517','fraction/year','data/demand/efficiency_gains_cagr.csv','260–289','Technology-share-weighted future total; generic nav columns overwritten','Do not apply unused0.2742 as final international-navigation efficiency'),
('ROAD_EV_SHARE','road','MANUAL_OVERRIDE','EV share','2025 .05;2030 .20;2035 .45;2040 .70;2045 .85;2050 1','fraction; stock/service interpretation unresolved','configs/config.asean.yaml','216–239','Multiplies energy proxy and cars-based capacities; exogenous','Not cost-optimal adoption'),
('ROAD_FCEV_SHARE','road','MANUAL_OVERRIDE','FCEV share','DEC2020–2050 all0','fraction','configs/config.asean.yaml','216–223','H2 Load only if share>0','Zero is scenario setting, not observed zero H2 potential'),
('SHIP_H2_SHARE','shipping','MANUAL_OVERRIDE','Shipping H2 share','DEC2020–2050 all0','fraction','configs/config.asean.yaml','232–239','Demand projection and terminal H2/oil split both consume share','Definitions across transformations require review'),
('VEHICLES','road','GLOBAL_HARMONIZED','Registered vehicle input','WHO GHO RS_194 + Wikipedia completion; fallback contains11 ASEAN rows','vehicles; year/class not retained','scripts/prepare_transport_data_input.py','37–112,162–199','cars allocate by population; set charger/Store capacity','Tutorial prepared transport_data absent; author input snapshot unknown'),
('FUEL_PROXY','road','DEFAULT','Average fuel efficiency proxy','(100−2014 transport CO2 share)/100; hardcoded fallback values','dimensionless; not kWh/km','scripts/prepare_transport_data_input.py','115–140','Divided by0.2 kWh/km×charger efficiency in downstream g','SYSTEM_LEVEL_UNIT_GAP; no physical fuel-economy conversion'),
('BEV_RATE','road','DEFAULT','BEV plug-to-wheel named efficiency','0.2','kWh/km per config comment','config.default.yaml','873','Used in fuel-efficiency ratio','Tesla Model S reference; not ASEAN aggregate fleet'),
('CHARGE_EFF','road','DEFAULT','Charging/V2G efficiency','0.9','dimensionless per Link','config.default.yaml','874','Applies to both charger and reverse V2G','Generic assumption; adoption/scientific acceptance pending'),
('FC_EFF','road;shipping','DEFAULT','Fuel cell efficiency','0.5','dimensionless assumed energy ratio','config.default.yaml','889','H2 final input=q/share-adjusted conversion','Energy/heat-value alignment pending'),
('ICE_EFF','road','DEFAULT','ICE efficiency','0.3','dimensionless assumed energy ratio','config.default.yaml','890','Oil Load=q×ICE share/efficiency','Aggregate proxy basis unresolved'),
('CHARGER_POWER','road','DEFAULT','Charger capacity','0.011','MW/registered vehicle','scripts/prepare_sector_network.py','2449–2469','Fixed cars×share×rate','Not installed ASEAN charging infrastructure'),
('EV_STORAGE','road','DEFAULT','EV energy/participation','0.05;0.5','MWh/vehicle; fraction participating','config.default.yaml','885–888','Fixed cars×EV share×battery energy×participation','Final strips Store; not functioning storage in author final'),
('AVAILABILITY','road','DEFAULT','Availability bounds','0.95 maximum;0.8 mean','fraction','config.default.yaml','881–882','Pkw weekly count maps to Link p_max_pu','No ASEAN charging behaviour evidence'),
('DSM','road','DEFAULT','SOC restriction','0.75 at07:00; v2g=true;bev_dsm=true','SOC fraction; hour; flags','config.default.yaml','883–886','Daily Store floor and reverse Link','Default true does not survive final Store strip'),
('PROFILE','road','EUROPE_INHERITED','Driving and availability profile','KFZ__count / Pkw__count; BASt2010–2015','hour-of-week vehicle counts','data/emobility/traffic.tex','6–13','Repeat weekly using first country timezone; weight/temperature normalization','Not ASEAN empirical profiles; not vehicle-km'),
('ROAD_TEMP','road','DEFAULT','Temperature deadband and corrections','15–20C; ICE/EV correction settings','C and configured proportional slopes','config.default.yaml','875–880','Applied to average consumption and road profile','Climate input global; response coefficients generic; exact-boundary conditional defect'),
('ROAD_SPACE','road;rail','GLOBAL_HARMONIZED','Nodal allocation','country population fractions','dimensionless shares','scripts/prepare_heat_data.py','149–160','country energy×population fraction; transport same input layout','Not road or rail network allocation; total conservation required'),
('WPI','shipping','GLOBAL_HARMONIZED','Port locations','NGA WPI; tutorial2026-09-29 user export/GDB mapping','coordinates; categorical harbor size','scripts/prepare_ports.py','21–31,120–137','country-normalized size1/2/3 then node map','Actual tutorial source is not proven paper source; no LA port'),
('AIRPORTS','aviation','GLOBAL_HARMONIZED','Airport locations','OurAirports processed cache; raw version UNKNOWN','coordinates; type; scheduled service','scripts/prepare_airports.py','19–77','filter scheduled medium/large withIATA; weights1/3','Not passenger throughput or bunker volume'),
('SHIP_EFF','shipping','DEFAULT','Shipping average efficiency','0.4','oil propulsion efficiency in2011 comment; doc conflict','config.default.yaml','979–980','H2 share×fuel total×0.4/FC efficiency','Year/definition/HHV-LHV unaccepted'),
('BUNKER','shipping;aviation','DEFAULT','International bunker flag','false','boolean emissions-scope switch','config.default.yaml','992','Domestic+international demand stays; false emission branch applies domestic fractions','Formula aggregates incorrectly across countries'),
('FUEL_HEAT','all','DEFAULT','Fuel mass conversion','diesel0.01194;jet kerosene0.01225;fuel oil0.01122','TWh/kt as used','scripts/_helpers.py','1837–1907','hardcoded factors cite UN energy methodology','Raw calorific basis not independently accepted'),
('FUEL_COST','all','UNKNOWN','Prepared fuel and conversion costs','Existing costs_2030_sec + v0.13.2 source chain; see retained cost trace','mixed EUR/year/capacity; efficiency/fuel units per source','Snakefile','1473','prepared costs consumed by sector network; annualized fixed and fuel terms','No new cost/DEA substitution; inherited unverified source-family acceptance'),
('ELECTRIC_PARENT','all','MANUAL_OVERRIDE','Research electricity parent','A* conceptual end-user final electricity; no numerical candidate accepted','MWh at agreed final-user boundary','../../buildings_heat/phase3a7/RESEARCH_ELECTRICITY_BOUNDARY_FREEZE.md','HDEC-P3A7-ELEC-001','Remove identified historical service input exactly once; future conversion endogenous','Concept frozen; country numeric containment pending')]
for id,mode,cls,item,value,unit,file,lines,trans,issue in params:
 local='evidence/source/U/'+file if not file.startswith('../') else file
 provenance.append(dict(ParameterID=id,Mode=mode,Country='ASEAN11/shared',Parameter=item,SourceClass=cls,SourceName='Frozen code/source registration; observed value is not accepted input',SourceURL=github+file if not file.startswith('../') else '',SourceFile=local,SourceYear='2014' if id=='FUEL_PROXY' else '2010–2015' if id=='PROFILE' else '2011 comment' if id=='SHIP_EFF' else 'UNKNOWN_OR_SCENARIO_YEAR',RawValue=value,RawUnit=unit,Transformation=trans,PyPSAValue=value,PyPSAUnit=unit,FinalCandidateValue='',Status='UNVERIFIED',HumanConfirmation='PENDING',EvidenceLocator=local+':'+lines,Issue=issue))
next(r for r in provenance if r['ParameterID']=='ELECTRIC_PARENT')['PyPSAValue']='NOT_IMPLEMENTED_AS_RESEARCH_ASTAR; numerical parent containment unresolved'
save('TRANSPORT_DATA_PROVENANCE',provenance)

items=[
('T01','A*与历史EV/rail包含关系','SYSTEM_LEVEL_BLOCKER','Demand + conversion duplicate or omission changes power/capacity/flows','Actual final-meter national parent; observed historical components and one-time transfer; unknown is not0','NoEV/rail parent subtraction; road electricity all empty-subset0','TRANSPORT_ELECTRICITY_DOUBLE_COUNT_AUDIT.md'),
('T02','Road能源代理与燃油效率量纲','SYSTEM_LEVEL_BLOCKER_IF_EXPLICIT_ROAD','Invalid proxy changes EV/H2/oil demand magnitude','Defensible aggregate energy/service conversion; no need all vehicle classes','CO2-share proxy divided bykWh/km','ROAD_TRANSPORT_AUDIT.md'),
('T03','Land与非电rail互斥','SYSTEM_LEVEL_BLOCKER_IF_BOTH_RETAINED','Same rail fuel represented in land and independent rail','One accounting owner; consistent demand transfer','land includes non-electricrail; rail constructor adds oil','RAIL_TRANSPORT_AUDIT.md'),
('T04','预测默认与缺失填零','SYSTEM_LEVEL_BLOCKER_FOR_NUMERIC_BASELINE','Magnitude and country pattern shifted by defaults/erased missing values','Review input families/year growth; preserve missing flag and correct subaccount handling','14base blanks→0;4road subaccounts→0;all countriesDEFAULT','TRANSPORT_DEMAND_SOURCE_TRACE.md'),
('T05','Shipping节点NaN与国家守恒','SYSTEM_LEVEL_BLOCKER_IF_SHIPPING_RETAINED','Oil/H2 obligations can disappear or shift countries','Finite nodal quantities; country totals preserved; root cause and mapping identity','39of48 oilNaN;1of48 H2NaN pre-strip','SHIPPING_AVIATION_AUDIT.md'),
('T06','国际bunker义务与国家归属','SYSTEM_LEVEL_BOUNDARY_DECISION','Large fuel obligation changes H2/power/country investment','Separate domestic and international obligation; report-country treatment; no automaticA* inclusion','Fuel demand retained even international_bunkers=false','SHIPPING_AVIATION_AUDIT.md'),
('T07','原power cap与共享Full-SC大气账','SYSTEM_LEVEL_BLOCKER','Different emissions scope changes technology selection/cost','Preserve original power-policy scope; explicit ledger/shared-fuel rules','GlobalConstraint has no power filter','TRANSPORT_CARBON_SCOPE_AUDIT.md'),
('T08','Rail油漏记与bunker排放加权','SYSTEM_LEVEL_BLOCKER_IF_FUEL_MODES_RETAINED','Omitted or misallocated CO2 changes constrained solution','Account complete combustion and country-weighted bunker emissions; no policy change','rail oil factor0/no combustion; scalar-region×country-ratio sum','TRANSPORT_CARBON_SCOPE_AUDIT.md'),
('T09','EV Store裁剪与灵活性声明','CONDITIONAL_SYSTEM_GATE','Invalid assumption of smart charging affects peaks/storage/interconnection','Choose fixed vs flexible scope; if flexible retain actual Store and justify capacity/availability','98V2G but0EV Stores in each author sample','ROAD_TRANSPORT_AUDIT.md'),
('T10','H2/FT义务、供给和预装电力','SYSTEM_LEVEL_ACCOUNTING_GATE','Duplicated fuel/electricity obligations change renewables/H2','Explicit terminal fuel accounts; endogenous production; exclude same preloaded electricity','Fixed H2 demand + production alone is normal','TRANSPORT_H2_FUEL_INTERACTION.md'),
('T11','共同时间权重/空间总量','SYSTEM_LEVEL_ACCOUNTING_GATE','Energy/peak/location differences affect capacity/flows','Consistent weights and country/node conservation; transparent proxies','BASt/population/ports/airports are different allocation mechanisms','TRANSPORT_TEMPORAL_SPATIAL_AUDIT.md'),
('T12','车辆、驾驶、充电桩、船/机子型','LIMITATION_NOT_DEFAULT_BLOCKER','Only conditional impact beyond retained aggregate obligations','Retain aggregate assumptions; reopen only on specific system-relevance evidence','No arbitrary detail-completeness prerequisite','TRANSPORT_TEMPORAL_SPATIAL_AUDIT.md'),
('T13','Vehicle stock/投资范围','LIMITATION_OR_CONDITIONAL_GATE','Fixed charger caps and omitted fleet capex limit investment interpretation','Declare energy-system cost; justify capacities if used; do not claim endogenous fleet cost','WHO year/class absent; vehicle investment not modeled','ROAD_TRANSPORT_AUDIT.md'),
('T14','Integrated/Disconnected对称边界','SYSTEM_LEVEL_COMPARISON_GATE','Changing demand/fuel trade/policy confounds interconnection effect','Same mode representation/demand/non-network assumptions; define cross-bordercarrier closure','No experiment executed','TRANSPORT_H2_FUEL_INTERACTION.md'),
('T15','原输入版本/单位/热值','INPUT_FAMILY_ACCEPTANCE_GATE','Unaccepted sources/factors change system quantities','Retained source bytes + compatible fuel/efficiency basis + human acceptance','Tutorial inputs are not paper manifest; no silent latest-data substitution','TRANSPORT_DATA_PROVENANCE.csv')]
material=[]
for id,item,status,path,min_e,obs,evidence in items:
 material.append(dict(ItemID=id,Item=item,Disposition=status,CredibleSystemImpactPath=path,MinimumClosureOrContainment=min_e,ObservedEvidence=obs,Evidence=evidence,NumericMaterialityThreshold='',QuantifiedEffect='',Stage='Before relevant numerical assembly/comparison; not blocker to this audit review',DecisionStatus='PROPOSED_TRIAGE_FOR_HUMAN_REVIEW',PatchExecuted='NO'))
save('TRANSPORT_MATERIALITY_REGISTER',material)

optionspec=[
('ROAD_AGG','Road aggregate','SYSTEM_RELEVANT_PENDING','EXPLICIT_EV_WITH_FIXED_SHARES; retained residual fuel','EMBEDDED final energy while explicit service conversion unresolved','T01;T02;T03;T04;T09;T10;T13;T15','Do not inherit dimensionally invalid proxy or pretend endogenous vehicle competition'),
('ROAD_PASS','Road passenger','EMBEDDED','Within auditable aggregate road; no separate mode split initially','Split only if material evidence justifies','T02;T04','No passenger-km evidence; no synthetic occupancy'),
('ROAD_FREIGHT','Road freight','EMBEDDED','Within auditable aggregate road; no forced independent fleet model','SYSTEM_RELEVANT_PENDING if freightH2 materially drives question','T02;T10','No tonne-km evidence; cannot allocate passenger shares to freight'),
('RAIL_E','Rail electricity','FIXED','Separate fixed account only after exact parent transfer','EMBEDDED with no extraLoad','T01;T03;T04;T11','Do not assert every country rail is negligible; one accounting owner'),
('RAIL_O','Rail fuel','FIXED','Retain documented non-electric fuel once, with complete CO2','Embedded direct fuel if no separate rail module','T03;T04;T08','No automatic zero for absent data; no need rail fleet competition'),
('SHIP_DOM','Domestic shipping','SYSTEM_RELEVANT_PENDING','FIXED fuel obligation + EXPLICIT existing supply paths','No automatic closure/removal for imperfect data','T04;T05;T06;T07;T08;T10;T15','Review volume,allocation,H2 share and carbon before numerical adoption'),
('SHIP_INT','International shipping','SYSTEM_RELEVANT_PENDING','Separate bunker obligation under reviewed territorial/reporting boundary','DEFER only by explicit scope decision, retaining limitation','T05;T06;T07;T08;T14','False bunker emissions switch is not an exclusion of demand'),
('AVI_DOM','Domestic aviation','SYSTEM_RELEVANT_PENDING','FIXED kerosene/oil obligation + EXPLICIT existing supply','No aircraft-type model required','T04;T06;T07;T08;T10;T15','FT supply potential does not require invented aircraft technology'),
('AVI_INT','International aviation','SYSTEM_RELEVANT_PENDING','Separate bunker obligation and country allocation','DEFER only by explicit human scope decision','T04;T06;T07;T08;T14','Do not automatically include in national final energy orA*'),
('ROAD_FCEV','Road FCEV','DEFERRED','Existing capability retained in audit; no positive share selected','SYSTEM_RELEVANT_PENDING if freightH2 decision requires it','T02;T07;T10','DEC default0 not accepted research optimal outcome'),
('SHIP_H2','Shipping H2','SYSTEM_RELEVANT_PENDING','Use existingH2 pathway only after explicit share/service decision','Keep base fuel obligation; no arbitrary H2 conversion','T05;T06;T07;T10','Potential system impact is not quantified or assumed positive'),
('FT_SUPPLY','FT and shared H2 supply','EXPLICIT','Candidate existing supply conversion for retained fuel obligations','Pending source/fuel/carbon and input-output checks','T07;T08;T10;T15','Does not freeze production levels or assert all fuel is synthetic'),
('EV_STORE','EV DSM/V2G','DEFERRED','Propose no unverified first-baseline flexibility credit','Conditional explicitstorage after justified stock/profile and finalretention','T09;T11;T13','This is a proposed restriction, not zero potential'),
('NH3_MARINE','Direct marineNH3/methanol/newblend','DEFERRED','Not present as transport end-use; no newtech thisphase','Only future specifically authorized model extension','T10;T15','IndustrialNH3 is not marineNH3'),
('OTHER_E','Other electric transport','EMBEDDED','Retain inside documented parent unless explicitly identified','Local pending subaccount; missing is not0','T01;T04','Do not invent separate demand for structural symmetry')]
options=[]
for id,mode,cls,preferred,alternative,gates,reason in optionspec:
 options.append(dict(ModeID=id,Mode=mode,CandidateClass=cls,ProposedFirstBaseline=preferred,AlternativeOrFallback=alternative,GateIDs=gates,Reason=reason,HumanDecision='PENDING_NOT_FROZEN',NumericInputsAccepted='NO',Implemented='NO'))
save('TRANSPORT_FIRST_FULLSC_OPTIONS',options)

# Preserve the user's actual scope and selected prior evidence; no old file mutation.
request=Path('C:/Users/20122/.codex/attachments/f7b1cb92-14ae-4e57-a180-798a9f854902/已粘贴的文本.txt')
(R/'evidence/USER_PHASE3B1_REQUEST.txt').write_bytes(request.read_bytes())
deps=['research/02_sector_coupling/buildings_heat/phase3a7/RESEARCH_ELECTRICITY_BOUNDARY_FREEZE.md','research/02_sector_coupling/buildings_heat/phase3a7/NEXT_SECTOR_HANDOFF.md','research/01_baseline_construction/CARBON_EQUIVALENCE_TEST.md','research/01_baseline_construction/PAPER_CARBON_ACCOUNTING.json','research/00_source_provenance/SECTOR_COUPLING_PROVENANCE.md','research/00_source_provenance/RESULTS_MEMBER_HASHES.json','research/00_source_provenance/RESULTS_PACKAGE_AUDIT.md','research/00_source_provenance/DEA_COST_SOURCE_TRACE.md','research/00_source_provenance/UNSD_REGISTRY_EVIDENCE.json','research/00_model_audit/input_snapshot/resources/baseline-aims-3H-tutorial/costs_2030_sec.csv']
manifest=[]
for name in deps:
 b=(ROOT/name).read_bytes();dest=R/'evidence/prior'/name;dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(b)
 manifest.append(dict(original_repo_path=name,copy=dest.relative_to(R).as_posix(),sha256=hashlib.sha256(b).hexdigest()))
(R/'evidence/PRIOR_INPUT_MANIFEST.json').write_text(json.dumps(manifest,indent=2),encoding='utf8')
print(json.dumps(dict(inventory=len(inventory),provenance=len(provenance),materiality=len(material),options=len(options))))
