solving:
  solver:
    name: highs
    options: sgp-simplex
  solver_options:
    sgp-simplex:
      threads: 1
      solver: simplex
      run_crossover: 'on'
      small_matrix_value: 1e-6
      large_matrix_value: 1e15
      primal_feasibility_tolerance: 1e-6
      dual_feasibility_tolerance: 1e-6
      ipm_optimality_tolerance: 1e-6
      parallel: 'off'
      random_seed: 123
